# build stage
FROM node:16.14.0-alpine as build

WORKDIR /usr/app
COPY package.json ./
COPY yarn.lock ./
RUN yarn install
COPY . .
RUN yarn build

# serve stage
FROM nginx:alpine
EXPOSE 80
COPY --from=build ./usr/app/build /usr/share/nginx/html
