services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
      - /usr/app/public/worker
