[package]
name = "rust_wasm"
version = "0.1.0"
authors = ["Mark Rikhter <markrihter98@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
num-complex = "0.4"
wasm-bindgen = "0.2"


[profile.release]
lto = true
